spring:
  datasource:
    url: jdbc:mysql://localhost/dept-4pm
    username: root
    password: techno
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
  servlet:
    context-path: /department
