spring:
  datasource:
    url: jdbc:mysql://localhost/emp-4pm
    username: root
    password: techno
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
  servlet:
    context-path: /employee
